-- 1. TRIGGER PARA ASIGNAR EL ID DE CATEGORIA
CREATE OR REPLACE TRIGGER TRG_CATEGORIA_BI
BEFORE INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
    :NEW.ID_CATEGORIA := SEC_ID_CATEGORIA.NEXTVAL;
    :NEW.FECHA_CREACION := SYSDATE;
END;
/

-- 2. TRIGGER PARA ASIGNAR EL ID (ANTES) DE PRODUCTO
CREATE OR REPLACE TRIGGER TRG_PRODUCTO_BI
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
    :NEW.ID_PRODUCTO := SEC_ID_PRODUCTO.NEXTVAL;
    :NEW.FECHA_CREACION := SYSDATE;
END;
/
-- 3. TRIGGER PARA ASIGNAR EL ID (ANTES) DE CLIENTE
CREATE OR REPLACE TRIGGER TRG_CLIENTE_BI
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    :NEW.ID_CLIENTE := SEC_ID_CLIENTE.NEXTVAL;
    :NEW.FECHA_REGISTRO := SYSDATE;
    :NEW.FECHA_CREACION := SYSDATE;
END;
/

-- 4. TRIGGER PARA ASIGNAR EL ID (ANTES) DE VENTA
CREATE OR REPLACE TRIGGER TRG_VENTA_BI
BEFORE INSERT ON VENTA
FOR EACH ROW
BEGIN
    :NEW.ID_VENTA := SEC_ID_VENTA.NEXTVAL;
    :NEW.USUARIO_REGISTRO := USER;
    :NEW.FECHA_CREACION := SYSDATE;
END;
/


--Crear la Bitacora de la tabla CATEGORIA
CREATE OR REPLACE TRIGGER TRG_CATEGORIA_AIU
AFTER INSERT OR UPDATE ON CATEGORIA
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10);
BEGIN
    IF INSERTING THEN V_ACCION := 'INSERT';
    ELSE V_ACCION := 'UPDATE';
    END IF;

    INSERT INTO CATEGORIA_BIT (
        ID_CATEGORIA_BIT, ID_CATEGORIA, NOMBRE, DESCRIPCION,
        FECHA_CREACION, FECHA_MODIFICACION, ACCION, IP
    ) VALUES (
        SEC_ID_CATEGORIA_BIT.NEXTVAL, :NEW.ID_CATEGORIA, :NEW.NOMBRE, :NEW.DESCRIPCION,
        :NEW.FECHA_CREACION, SYSDATE, V_ACCION, FN_GET_IP()
    );
END;
/


--Crear la Bitacora de la tabla PRODUCTO
CREATE OR REPLACE TRIGGER TRG_PRODUCTO_AIU
AFTER INSERT OR UPDATE ON PRODUCTO
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        V_ACCION := 'INSERT';
    ELSE
        V_ACCION := 'UPDATE';
    END IF;

    INSERT INTO PRODUCTO_BIT (
        ID_PRODUCTO_BIT, ID_PRODUCTO, NOMBRE, PRECIO, STOCK,
        ID_CATEGORIA, DESCRIPCION, ESTATUS, FECHA_CREACION,
        FECHA_MODIFICACION, ACCION, IP
    ) VALUES (
        SEC_ID_PRODUCTO_BIT.NEXTVAL, :NEW.ID_PRODUCTO, :NEW.NOMBRE, :NEW.PRECIO, :NEW.STOCK,
        :NEW.ID_CATEGORIA, :NEW.DESCRIPCION, :NEW.ESTATUS, :NEW.FECHA_CREACION,
        :NEW.FECHA_MODIFICACION, V_ACCION, FN_GET_IP()
    );
END;
/

--Crear la Bitacora de la tabla CLIENTE
CREATE OR REPLACE TRIGGER TRG_CLIENTE_AIU
AFTER INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10);
BEGIN
    IF INSERTING THEN V_ACCION := 'INSERT';
    ELSE V_ACCION := 'UPDATE';
    END IF;

    INSERT INTO CLIENTE_BIT (
        ID_CLIENTE_BIT, ID_CLIENTE, NOMBRE, APATERNO, AMATERNO,
        CORREO, TELEFONO, FECHA_REGISTRO, FECHA_CREACION,
        FECHA_MODIFICACION, ACCION, IP
    ) VALUES (
        SEC_ID_CLIENTE_BIT.NEXTVAL, :NEW.ID_CLIENTE, :NEW.NOMBRE, :NEW.APATERNO, :NEW.AMATERNO,
        :NEW.CORREO, :NEW.TELEFONO, :NEW.FECHA_REGISTRO, :NEW.FECHA_CREACION,
        SYSDATE, V_ACCION, FN_GET_IP()
    );
END;
/

--Crear a Bitacora de la tabla VENTAS
CREATE OR REPLACE TRIGGER TRG_VENTA_AIU
AFTER INSERT OR UPDATE ON VENTA
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10);
BEGIN
    IF INSERTING THEN V_ACCION := 'INSERT';
    ELSE V_ACCION := 'UPDATE';
    END IF;

    INSERT INTO VENTA_BIT (
        ID_VENTA_BIT, ID_VENTA, ID_CLIENTE, ID_PRODUCTO, CANTIDAD,
        FECHA_VENTA, USUARIO_REGISTRO, FECHA_CREACION, FECHA_MODIFICACION,
        ACCION, IP
    ) VALUES (
        SEC_ID_VENTA_BIT.NEXTVAL, :NEW.ID_VENTA, :NEW.ID_CLIENTE, :NEW.ID_PRODUCTO,
        :NEW.CANTIDAD, :NEW.FECHA_VENTA, :NEW.USUARIO_REGISTRO, :NEW.FECHA_CREACION,
        SYSDATE, V_ACCION, FN_GET_IP()
    );
END;
