--Ejecutar bloques anonimos para probar procedures

--PRUEBA DE REGISTRO DE VENTAS VALIDADAS
DECLARE
  v_res VARCHAR2(200);
BEGIN
  SP_REGISTRAR_VENTA(1, 1, 2, v_res);
  DBMS_OUTPUT.PUT_LINE(v_res);
END;

DECLARE
  v_res VARCHAR2(200);
BEGIN
  SP_REGISTRAR_VENTA(1, 1, 2, v_res);
  DBMS_OUTPUT.PUT_LINE(v_res);
END;
/

-- PRUEBA DE CALCULO DE SUBTOTAL DE UNA VENTA
-- Simulamos 5 productos a 100 pesos cada uno
SELECT FN_CALCULAR_SUBTOTAL(5, 100) AS RESULTADO_SUBTOTAL
FROM DUAL;

--PRUEBA PARA OBTENER IP
SELECT FN_GET_IP() AS IP FROM DUAL;

--PRUEBA PARA OBTENER IVA
SELECT FN_CALCULAR_IVA(100) AS IVA FROM DUAL;


